name:                sandbox-hs
version:             0.1.0.0
github:              "adomokos/sandbox-hs"
license:             BSD3
author:              "Attila Domokos"
maintainer:          "adomokos@gmail.com"
copyright:           "2018 Attila Domokos"

extra-source-files:
- README.md
- ChangeLog.md
ghc-options:
  - -Wall
  - -fno-warn-type-defaults

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/adomokos/sandbox-hs#readme>

dependencies:
  - base >= 4.7 && < 5
  - blaze-html
  - bytestring
  - containers
  - hourglass
  - lens
  - mtl
  - pretty
  - safe
  - template-haskell
  - text
  - time
  - transformers
  - unordered-containers
  - vector
  - xml-conduit
  - xml-hamlet

library:
  source-dirs: src

executables:
  sandbox-hs-exe:
    main:                Main.hs
    source-dirs:         app
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandbox-hs
  command-line-parser-exe:
    main:                Parser.hs
    source-dirs:         app
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - optparse-applicative

tests:
  sandbox-hs-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions:
    - OverloadedStrings
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandbox-hs
    - aeson
    - lens-aeson
    - aeson-pretty
    - attoparsec
    - conduit
    - hspec
    - lifted-async
    - say
    - stm
    - transformers
